export const equipment = {
  burningironsword: {
    equipped: true,
    name: "Burning Iron Sword",
    command: "burningironsword",
    type: "weapon",
    description: "A sturdy sword that deals a bit of damage.",
    damage: [1, 6],
    extra: [{ value: 2, type: "FIR" }],
  },
  icyhelmet: {
    equipped: false,
    name: "Icy Helmet",
    command: "icyhelmet",
    type: "head",
    description: "An icy helmet that protects your head.",
    AC: 1,
    resist: { WAT: 3 },
  },
  leathercap: {
    equipped: false,
    name: "Leather cap",
    command: "leathercap",
    type: "head",
    description: "a simple leather cap",
    AC: 1,
    hp: 5,
  },
  hotironshield: {
    equipped: true,
    name: "Hot Iron Shield",
    command: "hotironshield",
    type: "shield",
    description: "A sturdy shield that provides extra fire protection.",
    AC: 2,
    resist: { FIR: 1 },
  },
  icyleatherarmor: {
    equipped: true,
    command: "icyleatherarmor",
    name: "Icy Leather Armor",
    type: "armor",
    description: "Light armor that provides some protection.",
    AC: 3,
    resist: { WAT: 2 },
  },
  goblindagger: {
    equipped: true,
    name: "Goblin Dagger",
    command: "goblindagger",
    type: "weapon",
    description: "A small dagger that deals a bit of damage.",
    damage: [1, 4],
    extra: [],
  },
  goblindshield: {
    equipped: true,
    name: "Goblin Shield",
    command: "goblindshield",
    type: "shield",
    description: "A small shield that provides some protection.",
    AC: 2,
  },
  toxicgoblinhelmet: {
    equipped: true,
    name: "Toxic Goblin Helmet",
    command: "toxicgoblinhelmet",
    type: "armor",
    description: "A small helmet that protects you with poison resistance.",
    resist: { POI: 2 },
    AC: 1,
  },
  ratclaw: {
    equipped:true,
    name:"Rat Claw",
    command:"ratclaw",
    type:"weapon",
    description:"A dangerous and sharp claw",
    damage:[1,4],
    extra:[]
  }
};
