export const player = {
  name: "Lord Rick",
  description: "A brave warrior with a strong will and a heart of gold.",
  identified: true,
  conditions: [
    /* { name: "poisoned", duration: 3, stunned: false, damage: [{ type: "POI", value: 5 }] },
    { name: "iced", duration: 5, stunned: true, damage: [{ type: "WAT" }] },
    { name: "healing", duration: 5, stunned: false, stats: { hp: 5 } },*/
  ],
  stats: {
    hp: { base: 100, current: 100, bon: 0 },
    mp: { base: 20, current: 20, bon: 0 },
    pow: { base: 10, current: 10, bon: 0 },
    AC: { base: 5, current: 5, bon: 0 },
    STR: { base: 15, current: 15, bon: 0 },
    DEX: { base: 10, current: 10, bon: 0 },
    INT: { base: 12, current: 12, bon: 0 },
    resist: {
      FIR: { base: 5, current: 5, bon: 0 },
      POI: { base: 0, current: 0, bon: 0 },
      WAT: { base: 0, current: 0, bon: 0 },
      EAR: { base: 0, current: 0, bon: 0 },
      WIN: { base: 0, current: 0, bon: 0 },
      PHY: { base: 0, current: 0, bon: 0 },
    },
  },
  items: [
    {
      name: "Healing Orb",
      command: "healingorb",
      description: "Restores some health over time",
      amount: 1,
      effects: [{ name: "healing", duration: 5, stunned: false, stats: { hp: 5 } }],
    },
    {
      name: "Mega Potion",
      command: "megapotion",
      description: "Restores health, mana and power.",
      amount: 2,
      use: {
        hp: 10,
        mp: 10,
        pow: 10,
      },
    },
    {
      name: "Healing Potion",
      command: "healingpotion",
      description: "Restores some health.",
      amount: 2,
      use: {
        hp: 20,
      },
    },
    {
      name: "Potion of Wisdom",
      command: "potionofwisdom",
      description: "Increases INT for a short duration.",
      amount: 2,
      effects: [{ name: "intelligent", duration: 5, stunned: false, set: true, stats: { INT: 4 } }],
    },
    {
      name: "Mana Potion",
      command: "manapotion",
      description: "Restores some mana.",
      amount: 1,
      use: {
        mp: 5,
      },
    },
    {
      name: "Power Potion",
      command: "powerpotion",
      description: "Restores some power",
      amount: 1,
      use: {
        pow: 5,
      },
    },
  ],
  equipped: [
    {
      equipped: true,
      name: "Burning Iron Sword",
      command: "burningironsword",
      type: "weapon",
      description: "A sturdy sword that deals a bit of damage.",
      damage: [1, 6],
      extra: [{ value: 2, type: "FIR" }],
    },
    {
      equipped: false,
      name: "Icy Helmet",
      command: "icyhelmet",
      type: "head",
      description: "An icy helmet that protects your head.",
      AC: 1,
      resist: { WAT: 3 },
    },
    {
      equipped: false,
      name: "Leather cap",
      command: "leathercap",
      type: "head",
      description: "a simple leather cap",
      AC: 1,
      hp: 5,
    },
    {
      equipped: true,
      name: "Hot Iron Shield",
      command: "hotironshield",
      type: "shield",
      description: "A sturdy shield that provides extra fire protection.",
      AC: 2,
      resist: { FIR: 1 },
    },
    {
      equipped: true,
      command: "icyleatherarmor",
      name: "Icy Leather Armor",
      type: "armor",
      description: "Light armor that provides some protection.",
      AC: 3,
      resist: { WAT: 2 },
    },
  ],
  spellbook: [
    {
      name: "Healing Touch",
      command: "healingtouch",
      cost: 10,
      target: "player",
      stats: { hp: 20 },
      description: "Heals the target for a small amount of health.",
    },
    {
      name: "Fireball",
      command: "fireball",
      target: "enemy",
      cost: 5,
      extra: [{ type: "FIR", value: 20 }],
      description: "A powerful fire spell that deals damage to the enemy.",
    },
    {
      name: "Icicle",
      command: "icicle",
      target: "enemy",
      cost: 3,
      extra: [{ type: "WAT", value: 12 }],
      description: "A chilling spell that deals ice damage to the enemy.",
      effects: [{ name: "iced", duration: 2, stunned: true, damage: [{ type: "WAT" }] }],
    },
    {
      name: "Poison Cloud",
      command: "poisoncloud",
      target: "enemy",
      cost: 8,
      extra: [{ type: "POI", value: 10 }],
      description: "A poisenous cloud that deals damage over time.",
      effects: [{ name: "poisoned", duration: 5, stunned: false, damage: [{ type: "POI", value: 5 }] }],
    },
  ],
  specials: [
    {
      name: "Power Strike",
      command: "powerstrike",
      target: "enemy",
      cost: 10,
      extra: [{ type: "PHY", value: 25 }],
      description: "A powerful strike that deals extra damage to the enemy.",
    },
    {
      name: "Stamp",
      command: "stamp",
      target: "enemy",
      cost: 10,
      extra: [{ type: "PHY", value: 15 }],
      effects: [{ name: "stunned", duration: 1, stunned: true, damage: [{ type: "PHY" }] }],
      description: "A strong stamp on the ground that stunns your enemy",
    },
  ],
};
