export const spells = {
  healingtouch: {
    name: "Healing Touch",
    command: "healingtouch",
    cost: 10,
    target: "player",
    stats: { hp: 20 },
    description: "Heals the target for a small amount of health.",
  },
  fireball: {
    name: "Fireball",
    command: "fireball",
    target: "enemy",
    cost: 5,
    extra: [{ type: "FIR", value: 20 }],
    description: "A powerful fire spell that deals damage to the enemy.",
  },
  icicle: {
    name: "Icicle",
    command: "icicle",
    target: "enemy",
    cost: 3,
    extra: [{ type: "WAT", value: 12 }],
    description: "A chilling spell that deals ice damage to the enemy.",
    effects: [{ name: "iced", duration: 2, stunned: true, damage: [{ type: "WAT" }] }],
  },
  poisoncloud: {
    name: "Poison Cloud",
    command: "poisoncloud",
    target: "enemy",
    cost: 8,
    extra: [{ type: "POI", value: 10 }],
    description: "A poisenous cloud that deals damage over time.",
    effects: [{ name: "poisoned", duration: 5, stunned: false, damage: [{ type: "POI", value: 5 }] }],
  },
  fart: {
    name: "Fart",
    command: "fart",
    target: "player",
    cost: 3,
    effects: [{ name: "poisoned", duration: 10, stunned: false, damage: [{ type: "POI", value: 1 }] }],
    description: "a nasty fart that stinks for a long time",
  },
};
