const deps = [
  { name: "alva-zyklisch", dependencies: [] },
  { name: "b43n71_10h", dependencies: [] },
  { name: "ldbezuvw_Frueh", dependencies: [] },
  { name: "LGKK-PRE-Start", dependencies: [] },
  { name: "transfer_inverno_BKFP_files", dependencies: [] },
  { name: "ZUP_LGKK", dependencies: [] },
  { name: "transfer_ZUP_LGKK", dependencies: ["ZUP_LGKK"] },
  { name: "wcl_pkv_fehler_pruefung", dependencies: ["lzbddsou_2"] },
  { name: "ZUP_cleanup", dependencies: ["transfer_ZUP_LGKK"] },
  { name: "4_Update_L0Formular_Formulargruppe_ID", dependencies: ["gentoken"] },
  { name: "alva-ftp", dependencies: ["alva-zyklisch"] },
  { name: "SQL_Erstbearbeitung_Zweitbearbeitung_geaendert_ID", dependencies: ["lzbposab"] },
  { name: "SQL_TerminScriptRW", dependencies: ["SQL_Erstbearbeitung_Zweitbearbeitung_geaendert_ID"] },
  { name: "start-rpa-bot-02-dispatcher", dependencies: ["LGK-Batches-mit-Druckausgabe-Ende"] },
  { name: "LGKK-Start", dependencies: ["b13n07a"] },
  { name: "lkblan10", dependencies: ["erzeuge_SCHDAT_file"] },
  { name: "lzbauf90", dependencies: ["erzeuge_SCHDAT_file"] },
  { name: "lzbddsin", dependencies: ["ddsftp_lgkk_v"] },
  { name: "lzbddsou", dependencies: ["b38n66"] },
  { name: "lzbddsou_2", dependencies: ["l8aufall"] },
  { name: "lzbposab", dependencies: ["lzbddsou_2"] },
  { name: "lzbsydat_ende", dependencies: ["b21n29", "ddsftpgh_lgkk_2", "PDF_to_TEDA", "wcl_pkv_fehler_pruefung"] },
  { name: "lzbsydat_start", dependencies: ["deploy", "LGKK-PRE-Start"] },
  { name: "missing-address-pdf", dependencies: ["lgkk_pcl_handling"] },
  { name: "PDF_to_TEDA", dependencies: ["dda3_invaris_druckinfo"] },
  { name: "PKV-Block-Ende", dependencies: ["b34n61"] },
  { name: "PKV-Block-Start", dependencies: ["b06n06", "PKV-LEI-ENDE"] },
  { name: "ldbezuvw_online", dependencies: ["LGKK-Start"] },
  { name: "ldbprtdvds", dependencies: ["LGK-Batches-mit-Druckausgabe-Ende"] },
  { name: "ldbprtdvds_b31n57", dependencies: ["b31n57"] },
  { name: "ldbprtdvds-r", dependencies: ["ldbezuvw"] },
  { name: "LGK-Batches-mit-Druckausgabe-Ende", dependencies: ["b16n24", "b35n64", "b45n74"] },
  { name: "lgkk_binary_runtime_parser", dependencies: ["erzeuge_SCHDAT_file", "lkblan10", "lzbauf90"] },
  { name: "lgkk_cleanup_vor_tev", dependencies: ["gentoken"] },
  { name: "lgkk_pcl_handling", dependencies: ["ldbprtdvds-r"] },
  { name: "lgkk_pcl_handling_cleanup", dependencies: ["lgkk_cleanup_vor_tev"] },
  { name: "LGKK-Ende", dependencies: ["lgkk_binary_runtime_parser", "lzbsydat_ende"] },
  { name: "b43n72", dependencies: ["b43n71"] },
  { name: "b43n72_10h", dependencies: ["b43n71_10h"] },
  { name: "b45n74", dependencies: ["b35n64"] },
  { name: "b47n76", dependencies: ["b43n72"] },
  { name: "bkonstfilea", dependencies: ["bm00"] },
  { name: "bm00", dependencies: ["lzbsydat_start"] },
  { name: "copy_bilbetr-liste", dependencies: ["b13n07c"] },
  { name: "dda3_invaris_druckinfo", dependencies: ["missing-address-pdf"] },
  { name: "dda3_invaris_druckinfo_Frueh", dependencies: ["ddaerrors"] },
  { name: "ddacli_HB_HM_BESTELL_LISTE", dependencies: ["ldbprtdvds_b31n57"] },
  { name: "ddaerrors", dependencies: ["ldbezuvw_Frueh"] },
  { name: "ddsftp_dvs_IPXX", dependencies: ["ddsftpgh_lgkk"] },
  { name: "ddsftp_dvs_LGKK", dependencies: ["lzbddsin"] },
  { name: "ddsftp_lgkk_a", dependencies: ["lgkk_pcl_handling_cleanup"] },
  { name: "ddsftp_lgkk_ka", dependencies: ["b12_post_aix"] },
  { name: "ddsftp_lgkk_n", dependencies: ["ddsftp_lgkk_a"] },
  { name: "ddsftp_lgkk_v", dependencies: ["ddsftp_lgkk_n"] },
  { name: "ddsftpgh_dvs_b13n07", dependencies: ["dvsConverter_export_PFIF"] },
  { name: "ddsftpgh_dvs_eb", dependencies: ["dvsConverter_eb_IPXX"] },
  { name: "ddsftpgh_dvs_eb_LGKK", dependencies: ["dvsConverter_eb_LGKK"] },
  { name: "ddsftpgh_dvs_export", dependencies: ["dvsConverter_export_IPXX"] },
  { name: "ddsftpgh_dvs_IPXX", dependencies: ["dvsConverter_export_IPXX_2"] },
  { name: "ddsftpgh_dvs_LGKK_b10n26", dependencies: ["dvsConverter_export_LGKK"] },
  { name: "ddsftpgh_lgkk", dependencies: ["lzbddsou"] },
  { name: "ddsftpgh_lgkk_2", dependencies: ["lzbddsou_2"] },
  { name: "deploy", dependencies: ["LGKK-PRE-Start"] },
  { name: "dvsConverter_eb_IPXX", dependencies: ["dvsConverter_import_IPXX"] },
  { name: "dvsConverter_eb_LGKK", dependencies: ["dvsConverter_import_LGKK"] },
  { name: "dvsConverter_export_IPXX", dependencies: ["b47n76"] },
  { name: "dvsConverter_export_IPXX_2", dependencies: ["dvsConverter_fk_IPXX"] },
  { name: "dvsConverter_export_LGKK", dependencies: ["b10_post_aix"] },
  { name: "dvsConverter_export_PFIF", dependencies: ["b13_post_aix"] },
  { name: "dvsConverter_fk_IPXX", dependencies: ["b39n69"] },
  { name: "dvsConverter_import_IPXX", dependencies: ["ddsftp_dvs_IPXX"] },
  { name: "dvsConverter_import_LGKK", dependencies: ["ddsftp_dvs_LGKK"] },
  { name: "erzeuge_SCHDAT_file", dependencies: ["lzbsydat_ende"] },
  { name: "gentoken", dependencies: ["bkonstfilea"] },
  { name: "get_firmenname_from_pdf", dependencies: ["ddacli_HB_HM_BESTELL_LISTE"] },
  { name: "get_hema_fk", dependencies: ["b10_post_aix"] },
  { name: "hvbinout_cleanup", dependencies: ["ddsftpgh_dvs_export"] },
  { name: "L2A_update_sql", dependencies: ["SQL_TerminScriptRW"] },
  { name: "l8aufall", dependencies: ["hvbinout_cleanup"] },
  { name: "ldbezuvw", dependencies: ["ldbprtdvds"] },
  { name: "b02n22", dependencies: ["PKV-Block-Start"] },
  { name: "b02n23", dependencies: ["b02n22"] },
  { name: "b02n23_email_protokoll", dependencies: ["b02n23"] },
  { name: "b03_pre_aix", dependencies: ["ddsftpgh_dvs_IPXX"] },
  { name: "b03n06", dependencies: ["b03_pre_aix"] },
  { name: "b03n13", dependencies: ["b03n06"] },
  { name: "b04_post_aix", dependencies: ["b04n05"] },
  { name: "b04n04", dependencies: ["b03n13"] },
  { name: "b04n05", dependencies: ["b04n04"] },
  { name: "b05_post_aix", dependencies: ["b05n05"] },
  { name: "b05_pre_aix", dependencies: ["b04_post_aix"] },
  { name: "b05n02", dependencies: ["b05_pre_aix"] },
  { name: "b05n05", dependencies: ["b05n02"] },
  { name: "b06n06", dependencies: ["b05_post_aix"] },
  { name: "b07_pre_aix", dependencies: ["PKV-Block-Ende"] },
  { name: "b07n13", dependencies: ["b07_pre_aix"] },
  { name: "b07n14", dependencies: ["b07n13"] },
  { name: "b07n15", dependencies: ["b07n14"] },
  { name: "b07n16", dependencies: ["b07n14", "b07n15"] },
  { name: "b08n17", dependencies: ["b07n16"] },
  { name: "b09n30", dependencies: ["b08n17"] },
  { name: "b09n31", dependencies: ["b09n30"] },
  { name: "b10_post_aix", dependencies: ["b10n26"] },
  { name: "b10n26", dependencies: ["b02n22", "b02n23", "b28n56"] },
  { name: "b11_post_aix", dependencies: ["b11n27"] },
  { name: "b11_pre_aix", dependencies: ["b10_post_aix", "get_hema_fk"] },
  { name: "b11n27", dependencies: ["b11_pre_aix"] },
  { name: "b12_post_aix", dependencies: ["b12n28"] },
  { name: "b12n28", dependencies: ["b41n69"] },
  { name: "b13_post_aix", dependencies: ["b13n07c"] },
  { name: "b13_pre_aix", dependencies: ["ddsftp_lgkk_ka"] },
  { name: "b13n07a", dependencies: ["b13_pre_aix"] },
  { name: "b13n07b", dependencies: ["b09n31"] },
  { name: "b13n07c", dependencies: ["b13n07b"] },
  { name: "b14_post_aix", dependencies: ["b14n09", "b14n10"] },
  { name: "b14n08", dependencies: ["b11_post_aix"] },
  { name: "b14n09", dependencies: ["b11_post_aix", "b14n08"] },
  { name: "b14n10", dependencies: ["b14n09"] },
  { name: "b15n20", dependencies: ["b13n07c"] },
  { name: "b16n18", dependencies: ["b15n20", "b16-start"] },
  { name: "b16n23", dependencies: ["b16n18"] },
  { name: "b16n24", dependencies: ["b16n23"] },
  { name: "b16-start", dependencies: ["lzbsydat_start"] },
  { name: "b17n20", dependencies: ["b16n24"] },
  { name: "b17n21", dependencies: ["b17n20"] },
  { name: "b18n43", dependencies: ["LGK-Batches-mit-Druckausgabe-Ende"] },
  { name: "b18n44", dependencies: ["b18n43"] },
  { name: "b18n45", dependencies: ["b18n44"] },
  { name: "b19n52", dependencies: ["b18n45"] },
  { name: "b19n53", dependencies: ["b19n52"] },
  { name: "b21n29", dependencies: ["L2A_update_sql"] },
  { name: "b22n11", dependencies: ["b17n21"] },
  { name: "b24n41", dependencies: ["b19n53"] },
  { name: "b24n42", dependencies: ["b24n41"] },
  { name: "b25n25", dependencies: ["b19n53", "b24n42"] },
  { name: "b25n26", dependencies: ["b25n25"] },
  { name: "b27_post_aix", dependencies: ["b27n46"] },
  { name: "b27n46", dependencies: ["b22n11"] },
  { name: "b28n56", dependencies: ["b02n22", "b02n23"] },
  { name: "b30_post_aix", dependencies: ["b30n55"] },
  { name: "b30n55", dependencies: ["b25n25"] },
  { name: "b31_post_aix", dependencies: ["b31n57b"] },
  { name: "b31n57", dependencies: ["b27_post_aix"] },
  { name: "b31n57b", dependencies: ["get_firmenname_from_pdf"] },
  { name: "b33n60", dependencies: ["b30_post_aix"] },
  { name: "b34n61", dependencies: ["b14_post_aix"] },
  { name: "b35n63", dependencies: ["b31_post_aix"] },
  { name: "b35n64", dependencies: ["b35n63"] },
  { name: "b37n65", dependencies: ["b30_post_aix", "b33n60"] },
  { name: "b38n66", dependencies: ["ldbezuvw_online"] },
  { name: "b39n67", dependencies: ["ddsftpgh_dvs_eb"] },
  { name: "b39n68", dependencies: ["b39n67"] },
  { name: "b39n69", dependencies: ["b39n68"] },
  { name: "b40n68", dependencies: ["b37n65"] },
  { name: "b41n69", dependencies: ["ddsftpgh_dvs_eb_LGKK"] },
  { name: "b42n70", dependencies: ["b40n68"] },
  { name: "b42n72", dependencies: ["b40n68", "b42n70"] },
  { name: "b43n71", dependencies: ["b40n68", "b42n70", "b42n72"] },
];

// jobConfig to apply on multiple jobs
const config = {
  ".*ftp.*": { color: "coral" },
  ".*dvs.*": { color: "BlueViolet" },
  ".*aix.*": { color: "BurlyWood",dashed:true,strokeColor:"BurlyWood" },
  "b[0-9][0-9]n[0-9][0-9].*": { color: "DarkSeaGreen" },
};
